### ISSUE TITLE
how run as desktop application?

### ISSUE THREAD

**Issue by sussyboiiii** [nat/openplayground#38]
Hello,
I have tried the web gui and found it quite nice, but I was wondering if it would be possible to run even just one model as an application outside of a web server completely "locally" idk how to explain this better, basically just having the ability to run models with a gui as an application not web server on a computer to get a ChatGPT like experience but completely just outside of the browser like searching in explorer or finder even if thats a terrible example.
Thanks!

**Comment by AlexanderLourenco** [comment]
Hi! 

Technically you can already achieve this since there's no special authentication logic for the API: https://github.com/nat/openplayground/tree/main/server/lib/api

e.g: If you were to visit http://localhost:5432/api/models it will return a JSON array with all models on record, whereas http://localhost:5432/api/models-enabled returns an object of {provider:model-name}-> model details for models that are ready to go (the first API call also contains models that are currently not ready for completions, like HF models that are yet to be downloaded or have been disabled).

Completions are Server Side Events, but if you don't need streaming we could introduce a POST request to return the entire completion.

I will assign myself the task of documenting the API but if someone else wants to take charge of that do let me know! :)

**Comment by sussyboiiii** [comment]
Thank you for your response, 

I believe my first message was a bit all over the place.

So, the thing I ment is a desktop application to run different models on e.g. via  llama.cpp, or the OpenAI API.
Not to compare models just to set it up and have a desktop application with "your own" assistant or how you want to call it.
The parameters could be modified in the main file or in a .txt file.
